import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Banners from "@/components/Homepage/Banners";
import Specifications from "@/components/Homepage/Specifications";
import Features from "@/components/Homepage/Features";
import Cover from "@/components/Homepage/Cover";
import Maintenance from "@/components/Homepage/Maintenance";
import Products from "@/components/Homepage/Products";
import GetInTouch from "@/components/Homepage/GetInTouch";

const inter = Inter({ subsets: ["latin"] });

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Sky Water Pump</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <Banners></Banners>
      <Specifications></Specifications>
      <Features></Features>
      <Cover></Cover>
      <Maintenance></Maintenance>
      <Products productsData={props.productsData}></Products>
      <GetInTouch></GetInTouch>
      <Footer></Footer>
    </>
  );
}

export async function getServerSideProps(context) {
  const { params, req, res } = context;

  const response = await fetch("http://localhost:4000/products");
  const productsData = await response.json();

  return {
    props: {
      productsData: productsData,
    },
  };
}
